server.netty.websocket.crypto.enable=true
server.netty.websocket.crypto.algorithm=AES-GCM
server.netty.websocket.crypto.key-id=demo-2026-05
server.netty.websocket.crypto.key-provider=demoProvider
server.netty.websocket.crypto.include-uris=/ws/test,/ws/json
