/*
 * Copyright 2018 berrywang1996
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.berrywang1996.netty.spring.web.mvc.context;

import java.io.File;
import java.io.InputStream;

/**
 * Encapsulates a file download response, wrapping the file data, filename, and content type
 * so that controller methods can trigger browser file downloads cleanly.
 *
 * <p>Supports three data sources:
 * <ul>
 *   <li>{@link File} — streamed via zero-copy if possible</li>
 *   <li>{@code byte[]} — in-memory content</li>
 *   <li>{@link InputStream} — streaming source</li>
 * </ul>
 *
 * <p>When a controller method returns a {@code FileDownload} (or wraps it in
 * {@link ResponseEntity}), the framework bypasses the normal view handler and writes
 * the binary content directly, setting {@code Content-Disposition: attachment} to trigger
 * a browser download.
 *
 * <p>Usage examples:
 * <pre>{@code
 * // Download a file from disk
 * @GetMapping("/download")
 * public FileDownload download() {
 *     return FileDownload.fromFile(new File("/data/report.pdf"));
 * }
 *
 * // Download generated bytes with custom filename
 * @GetMapping("/export")
 * public FileDownload export() {
 *     byte[] csv = generateCsv();
 *     return FileDownload.fromBytes(csv, "export.csv", "text/csv");
 * }
 *
 * // Download with ResponseEntity for status/header control
 * @GetMapping("/report")
 * public ResponseEntity<FileDownload> report() {
 *     FileDownload file = FileDownload.fromFile(new File("/data/report.pdf"));
 *     return ResponseEntity.ok().body(file);
 * }
 *
 * // Inline display (e.g. show PDF in browser)
 * @GetMapping("/preview")
 * public FileDownload preview() {
 *     return FileDownload.fromFile(new File("/data/doc.pdf")).inline();
 * }
 * }</pre>
 *
 * @author berrywang1996
 * @since V1.5.0
 */
public class FileDownload {

    /** The download filename presented to the browser (Content-Disposition). */
    private final String filename;

    /** The MIME content type. */
    private final String contentType;

    /** File source (exclusive with bytes/inputStream). */
    private final File file;

    /** Byte array source (exclusive with file/inputStream). */
    private final byte[] bytes;

    /** InputStream source (exclusive with file/bytes). */
    private final InputStream inputStream;

    /** Content length hint (-1 = unknown, used for InputStream sources). */
    private final long contentLength;

    /** Whether to use inline disposition (display in browser) instead of attachment (download). */
    private boolean inline;

    private FileDownload(String filename, String contentType, File file,
                         byte[] bytes, InputStream inputStream, long contentLength) {
        this.filename = filename;
        this.contentType = contentType;
        this.file = file;
        this.bytes = bytes;
        this.inputStream = inputStream;
        this.contentLength = contentLength;
        this.inline = false;
    }

    // ----- Static factory methods -----

    /**
     * Creates a download from a {@link File} on disk.
     *
     * <p>The filename and content type are derived from the file automatically.
     * Content type defaults to {@code "application/octet-stream"} if not determinable.
     *
     * @param file the file to download
     * @return a new {@code FileDownload}
     * @throws IllegalArgumentException if the file does not exist or is not readable
     */
    public static FileDownload fromFile(File file) {
        if (file == null || !file.exists() || !file.isFile()) {
            throw new IllegalArgumentException("File does not exist or is not a regular file: " + file);
        }
        String contentType = guessContentType(file.getName());
        return new FileDownload(file.getName(), contentType, file, null, null, file.length());
    }

    /**
     * Creates a download from a {@link File} with a custom download filename.
     *
     * @param file     the file to download
     * @param filename the filename presented to the browser
     * @return a new {@code FileDownload}
     * @throws IllegalArgumentException if the file does not exist or is not readable
     */
    public static FileDownload fromFile(File file, String filename) {
        if (file == null || !file.exists() || !file.isFile()) {
            throw new IllegalArgumentException("File does not exist or is not a regular file: " + file);
        }
        String contentType = guessContentType(filename);
        return new FileDownload(filename, contentType, file, null, null, file.length());
    }

    /**
     * Creates a download from a byte array.
     *
     * @param bytes       the file content
     * @param filename    the download filename
     * @param contentType the MIME type (e.g. "application/pdf", "text/csv")
     * @return a new {@code FileDownload}
     */
    public static FileDownload fromBytes(byte[] bytes, String filename, String contentType) {
        if (bytes == null) {
            throw new IllegalArgumentException("Bytes must not be null");
        }
        if (filename == null || filename.isEmpty()) {
            throw new IllegalArgumentException("Filename must not be null or empty");
        }
        return new FileDownload(filename, contentType, null, bytes, null, bytes.length);
    }

    /**
     * Creates a download from a byte array with auto-detected content type.
     *
     * @param bytes    the file content
     * @param filename the download filename
     * @return a new {@code FileDownload}
     */
    public static FileDownload fromBytes(byte[] bytes, String filename) {
        return fromBytes(bytes, filename, guessContentType(filename));
    }

    /**
     * Creates a download from an {@link InputStream}.
     *
     * <p>The stream is consumed once when writing the response and should not be reused.
     *
     * @param inputStream   the data source
     * @param filename      the download filename
     * @param contentType   the MIME type
     * @param contentLength the content length (-1 if unknown; chunked transfer will be used)
     * @return a new {@code FileDownload}
     */
    public static FileDownload fromStream(InputStream inputStream, String filename,
                                          String contentType, long contentLength) {
        if (inputStream == null) {
            throw new IllegalArgumentException("InputStream must not be null");
        }
        return new FileDownload(filename, contentType, null, null, inputStream, contentLength);
    }

    /**
     * Creates a download from an {@link InputStream} with unknown content length.
     *
     * @param inputStream the data source
     * @param filename    the download filename
     * @param contentType the MIME type
     * @return a new {@code FileDownload}
     */
    public static FileDownload fromStream(InputStream inputStream, String filename, String contentType) {
        return fromStream(inputStream, filename, contentType, -1);
    }

    // ----- Configuration methods -----

    /**
     * Switches the Content-Disposition from {@code attachment} (download) to {@code inline}
     * (display in browser). Useful for PDFs, images, and other browser-renderable formats.
     *
     * @return this {@code FileDownload} for chaining
     */
    public FileDownload inline() {
        this.inline = true;
        return this;
    }

    // ----- Getters -----

    /**
     * Returns the download filename.
     *
     * @return the filename for the Content-Disposition header
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Returns the MIME content type.
     *
     * @return the content type string
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Returns the {@link File} source, or {@code null} if the data comes from bytes/stream.
     *
     * @return the file source, or null
     */
    public File getFile() {
        return file;
    }

    /**
     * Returns the byte array source, or {@code null} if the data comes from file/stream.
     *
     * @return the byte content, or null
     */
    public byte[] getBytes() {
        return bytes;
    }

    /**
     * Returns the {@link InputStream} source, or {@code null} if the data comes from file/bytes.
     *
     * @return the input stream, or null
     */
    public InputStream getInputStream() {
        return inputStream;
    }

    /**
     * Returns the content length, or -1 if unknown.
     *
     * @return the content length in bytes
     */
    public long getContentLength() {
        return contentLength;
    }

    /**
     * Returns whether the content should be displayed inline in the browser.
     *
     * @return {@code true} for inline, {@code false} for attachment (download)
     */
    public boolean isInline() {
        return inline;
    }

    // ----- Utility -----

    /**
     * Guesses the MIME type from the filename extension.
     * Falls back to {@code "application/octet-stream"} for unknown types.
     *
     * @param filename the filename to inspect
     * @return a MIME type string
     */
    private static String guessContentType(String filename) {
        if (filename == null) {
            return "application/octet-stream";
        }
        String lower = filename.toLowerCase();
        if (lower.endsWith(".pdf")) return "application/pdf";
        if (lower.endsWith(".json")) return "application/json";
        if (lower.endsWith(".xml")) return "application/xml";
        if (lower.endsWith(".zip")) return "application/zip";
        if (lower.endsWith(".gz") || lower.endsWith(".gzip")) return "application/gzip";
        if (lower.endsWith(".tar")) return "application/x-tar";
        if (lower.endsWith(".csv")) return "text/csv";
        if (lower.endsWith(".txt")) return "text/plain";
        if (lower.endsWith(".html") || lower.endsWith(".htm")) return "text/html";
        if (lower.endsWith(".css")) return "text/css";
        if (lower.endsWith(".js")) return "application/javascript";
        if (lower.endsWith(".png")) return "image/png";
        if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) return "image/jpeg";
        if (lower.endsWith(".gif")) return "image/gif";
        if (lower.endsWith(".svg")) return "image/svg+xml";
        if (lower.endsWith(".ico")) return "image/x-icon";
        if (lower.endsWith(".webp")) return "image/webp";
        if (lower.endsWith(".mp3")) return "audio/mpeg";
        if (lower.endsWith(".mp4")) return "video/mp4";
        if (lower.endsWith(".wav")) return "audio/wav";
        if (lower.endsWith(".doc")) return "application/msword";
        if (lower.endsWith(".docx")) return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        if (lower.endsWith(".xls")) return "application/vnd.ms-excel";
        if (lower.endsWith(".xlsx")) return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        if (lower.endsWith(".ppt")) return "application/vnd.ms-powerpoint";
        if (lower.endsWith(".pptx")) return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        return "application/octet-stream";
    }

    @Override
    public String toString() {
        return "FileDownload{" +
                "filename='" + filename + '\'' +
                ", contentType='" + contentType + '\'' +
                ", contentLength=" + contentLength +
                ", inline=" + inline +
                '}';
    }

}
